rabbit:
    host: rabbit.fluency.com
    port: 5672
    user: site
    password: site
    queue_on_split: queue_on_split
    queue_splited: queue_splited

mongo:
  host: mongo.fluency.com
  database: fluency

